apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  labels:
    pro: roboshop
spec:
  containers:
  - name: debug-Cont
    image: veenay910/debug
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
