apiVersion: app/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop-dev
  lables: 
    pro: roboshop
    componenet: mongodb
    tier: db
    spec:
      replicas: 1
      selector:
        matchLabels:
           pro: roboshop
           omponenet: mongodb
           tier: db
      template:
        metadata:
          labels:
            pro: roboshop
            componenet: mongodb
            tier: db
        spec:
          containers:
            - name: myapp
              image: veenay910/mongo-init-image:11
    