apiVersion: v1
kind: Pod
metadata:
  name: fe
  labels:
    pro: roboshop
    component: fe
    tier: fe
spec:
  containers:
  - name: nginx
    image: veenay910/fe:v1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
